/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { ITCO2Faucet, ITCO2FaucetInterface } from "../ITCO2Faucet";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_erc20Address",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_amount",
        type: "uint256",
      },
    ],
    name: "withdraw",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ITCO2Faucet__factory {
  static readonly abi = _abi;
  static createInterface(): ITCO2FaucetInterface {
    return new utils.Interface(_abi) as ITCO2FaucetInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ITCO2Faucet {
    return new Contract(address, _abi, signerOrProvider) as ITCO2Faucet;
  }
}
